version: "3.9"

services:
  ansible_control_node:
    build:
      context: .
      dockerfile: ./ansible-control-node/Dockerfile
    container_name: ansible_control_node
    tty: true
    volumes:
      - ../pg-deployer:/pg-deployer
  debian_host:
    build:
      context: .
      dockerfile: ./debian/Dockerfile
    container_name: debian_ssh
    ports:
      - "2222:22"
    tty: true
  almalinux_host:
    build:
      context: .
      dockerfile: almalinux/Dockerfile
    container_name: almalinux_ssh
    ports:
      - "2223:22"
    tty: true